### PR TITLE
Update EventResponse with event type

### PR DESCRIPTION
**Pull request by tyvdh**

### CODE REVIEW

**Review by Shaptic — APPROVED** [review]
nice catch :clap:

**Comment by Shaptic** [comment]
mind adding a changelog entry?

**Comment by tyvdh** [comment]
Is that a manual process? I have not added a changelog entry for this repo yet. Anything special to be aware of?

**Comment by Shaptic** [comment]
It's manual, yeah - think of it as documentation heh. Just follow the existing format!

**Pull request merged**
