### PR TITLE
Release v0.7.1, fixing browser bundling bugs.

### LINKED ISSUE #94: Server constructor error in browser v0.7.0
**Describe the bug**
- soroban-client does not works with browser / Client Components
- it did work in v0.5.1

So. I did two experiments:
1) A brand new create-react-app
2) A brand new create-next-app

In both I installed soroban-client 0.7.0. Without installing @soroban-react.

The code added is very simple:

```
import SorobanClient from "soroban-client";
const myServer = new SorobanClient.Server('https://soroban-rpc.stellar.org');
console.log(myServer)
```

With create-react-app: https://github.com/esteblock/create-react-app-soroban-client/tree/soroban-client%400.7.0
With next: https://github.com/esteblock/my-next-app-soroban-client/tree/soroban-client-0.7.0

With both of them I encounter the same error. 

1) With create-react-app I got:
```
Uncaught TypeError: soroban_client__WEBPACK_IMPORTED_MODULE_2___default(...).Server is not a constructor
    at ./src/App.js (App.js:5:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.js (App.js:29:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
```

2) With Next:
At the begginig I was not having any problem. But I was not having any console.log in the browser either (Console.log in the console was working fine)
This is because by default, Next.js uses Server Components.
After I added "use client" at the top, to make it a Client Component I got the same problem:

```
Unhandled Runtime Error

TypeError: soroban_client__WEBPACK_IMPORTED_MODULE_1___default().Server is not a constructor
Source

src/app/page.tsx (6:17) @ <unknown>

  4 | import styles from './page.module.css'
  5 | 
> 6 | const myServer = new SorobanClient.Server('https://soroban-rpc.stellar.org');
    |                 ^
  7 | console.log(myServer)
```

So this enforces my theory about webpack changes introduced in https://github.com/stellar/js-soroban-client/compare/v0.5.1...v0.6.0

Should we move to an issue in js-soroban-client?

___

When I install soroban-client@0.5.1 works OK, both with create-react-app and next

https://github.com/esteblock/create-react-app-soroban-client/tree/soroban-client%400.5.1
https://github.com/esteblock/my-next-app-soroban-client/tree/soroban-client%400.5.1

___

**Additional context**
bug reported: https://github.com/esteblock/soroban-react/issues/30 and https://github.com/esteblock/soroban-react/pull/28#issuecomment-1554847236

### PR DESCRIPTION
**Pull request by Shaptic**
This partially fixes #94, allowing the library to be imported as:

```ts
import * as SorobanClient from 'soroban-client';
```

in browser environments.

It also broadens the bundles' JS compatibility, reverting #90.

### CODE REVIEW

**Comment by Shaptic** [comment]
tagging @esteblock, @piyalbasu, and @sreuland for review

**Review by piyalbasu — APPROVED** [review]

**Review by sreuland — APPROVED** [review]
nice, do you by chance know why the existing headless browser tests for chrome/firefox didn't replicate the same problem? those tests use the /dist correct? seems like [constructor_test.js](https://github.com/stellar/js-soroban-client/blob/webpack-export-defaults/test/unit/server/constructor_test.js) should have tripped on it also.

**Comment by esteblock** [comment]
I tried and worked both for my create-react-app and my-next-app experiments.
Now will try with the library

**Comment by Shaptic** [comment]
To be honest, I don't know. Karma relies on `karma.conf.js` to inject stuff into the webpack config, so maybe there is some magic happening there... in `test/test-browser.js`, there's not even a need for an import.

**Comment by esteblock** [comment]
Worked in @soroban-react!
For now I did a new alpha release:

Changes:
 - @soroban-react/chains: 4.5.1-alpha.0 => 4.5.1-alpha.1
 - @soroban-react/connect-button: 4.5.1-alpha.0 => 4.5.1-alpha.1
 - @soroban-react/contracts: 4.5.1-alpha.0 => 4.5.1-alpha.1
 - @soroban-react/core: 4.5.1-alpha.0 => 4.5.1-alpha.1
 - @soroban-react/events: 4.5.1-alpha.0 => 4.5.1-alpha.1
 - @soroban-react/utils: 4.5.1-alpha.0 => 4.5.1-alpha.1
 - @soroban-react/wallet-data: 4.5.1-alpha.0 => 4.5.1-alpha.1


Waiting for 0.7.1 !

**Pull request merged**
